name: Build

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

  workflow_dispatch: {}

jobs:
  build:
    permissions:
      checks: write
      statuses: write
      contents: read
      packages: write

    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3.1.0
        with:
          fetch-depth: 0

      - name: Set image
        shell: bash
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          IMAGE=ghcr.io/tietoevry-dataplatforms/actions-app-token:$IMAGE_TAG

          set | grep ^IMAGE >> $GITHUB_ENV

      - name: Docker login
        shell: bash
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u USERNAME ghcr.io --password-stdin

      - name: Build docker image
        shell: bash
        run: |
          docker build . -t $IMAGE

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE }}
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Run test
        shell: bash
        env:
          INPUT_APP_ID: ${{ secrets.APP_ID }}
          INPUT_APP_PEM: ${{ secrets.APP_PEM }}
        run: docker run -e INPUT_APP_ID -e INPUT_APP_PEM -e GITHUB_API_URL -e GITHUB_REPOSITORY $IMAGE

      - name: Release docker image
        shell: bash
        if: github.ref == 'refs/heads/main'
        run: docker push $IMAGE
